### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by VictorVuSon** [lgaticaq/redis-sentinel#17]
Hi, I am hitting a problem, could you please help me out.
I run Redis as name master container in port 6379.
I also run 
docker run -d --name redis-sentinel-01 --link master:master -p 32801:26379 lgatica/redis-sentinel
When I try to connect to sentinel, my source like that:
 "host": "192.168.0.32",
 "port": 32801
But I got this error: Potentially unhandled rejection [2] Error: Failed to find a sentinel from the endpoints
Please explain what's Im wrong. Thanks

**Comment by lgaticaq** [comment]
Hello. I did tests with node and it works.

This is the commands to run containers.

```bash
docker run -d --name master -p 6379:6379 redis:4.0.2-alpine
docker run -d --name redis-sentinel-01 --link master:master -p 32801:26379 lgatica/redis-sentinel:4.0.2
```

And this is my code test.

```node
const Redis = require('ioredis')

const redis = new Redis({sentinels: [{ host: 'localhost', port: 32801 }], name: 'master'})

redis.set('foo', 'bar').then(() => {
  redis.get('foo').then(reply => {
    // reply === 'bar'
  })
})
```

**Comment by VictorVuSon** [comment]
Thank you for your time!
Can I use for sentinel like my code: 
It's still have an error.
Can you please take a look.
import Sentinel from 'redis-sentinel';
        const endpoints = [
      {
        "host": "192.168.0.155",
        "port": 32801
      },
      {
        "host": "192.168.0.155",
        "port": 6379
      },
      {
        "host": "192.168.0.155",
        "port": 6379
      }
    ];
       const sentinel = Sentinel.Sentinel(endpoints);
       const redis = sentinel.createClient('mymaster', {});

**Comment by lgaticaq** [comment]
I show two errors en your code. The endpoints and master name. The correct code is:
```javascript
import Sentinel from 'redis-sentinel'

const endpoints = [{host: '192.168.0.155', port: 32801}] // sentinel endpoints
const sentinel = Sentinel.Sentinel(endpoints)
const redis = sentinel.createClient('master', {}) // Default master name in my docker image es "master"
```

**Comment by lgaticaq** [comment]
Close issue for not respond
