### ISSUE TITLE
Unable to run some command (GET, SET...)

### ISSUE THREAD

**Issue by enekenasoa** [lgaticaq/redis-sentinel#18]
Hi I'm running on the docker-compose way and it looks running well. 
But when I'm trying to test the set command (as get, keys...), it shows "unknown command" 

_

> 192.168.0.1:61026> set
> (error) ERR unknown command 'set'

> 192.168.0.1:61026> KEYS *
> (error) ERR unknown command 'KEYS'

_

I am able to get some help command information
_
> 192.168.0.1:61026> help set
> 
>   SET key value [EX seconds] [PX milliseconds] [NX|XX]
>   summary: Set the string value of a key
>   since: 1.0.0
>   group: string
_

But when I'm trying to use it, it gets this issue

If needed , here's my server info

_
> 192.168.0.1:61026> info
> # Server
> redis_version:4.0.7
> redis_git_sha1:00000000
> redis_git_dirty:0
> redis_build_id:f295d9beb14f1ade
> redis_mode:sentinel
> os:Linux 4.9.12-rancher x86_64
> arch_bits:64
> multiplexing_api:epoll
> atomicvar_api:atomic-builtin
> gcc_version:6.4.0
> process_id:15
> run_id:ed5701e5ef09fc248e02b29f13f15de80d67251a
> tcp_port:26379
> uptime_in_seconds:322608
> uptime_in_days:3
> hz:11
> lru_clock:7257831
> executable:/redis/redis-server
> config_file:/redis/sentinel.conf
> 
> # Clients
> connected_clients:1
> client_longest_output_list:0
> client_biggest_input_buf:0
> blocked_clients:0
> 
> # CPU
> used_cpu_sys:387.50
> used_cpu_user:237.32
> used_cpu_sys_children:0.00
> used_cpu_user_children:0.00
> 
> # Stats
> total_connections_received:18
> total_commands_processed:4
> instantaneous_ops_per_sec:0
> total_net_input_bytes:3210
> total_net_output_bytes:4849
> instantaneous_input_kbps:0.00
> instantaneous_output_kbps:0.00
> rejected_connections:0
> sync_full:0
> sync_partial_ok:0
> sync_partial_err:0
> expired_keys:0
> evicted_keys:0
> keyspace_hits:0
> keyspace_misses:0
> pubsub_channels:0
> pubsub_patterns:0
> latest_fork_usec:0
> migrate_cached_sockets:0
> slave_expires_tracked_keys:0
> active_defrag_hits:0
> active_defrag_misses:0
> active_defrag_key_hits:0
> active_defrag_key_misses:0
> 
> # Sentinel
> sentinel_masters:1
> sentinel_tilt:0
> sentinel_running_scripts:0
> sentinel_scripts_queue_length:0
> sentinel_simulate_failure_flags:0
> master0:name=master,status=ok,address=10.42.192.4:6379,slaves=1,sentinels=1

_

Thanks

**Comment by lgaticaq** [comment]
Hello, do you execute this commands (set, get, keys, etc) in sentinel container or redis container. Please paste your docker-compose.yml for replicate error

**Comment by enekenasoa** [comment]
Hello @lgaticaq,
I'm running it on the sentinel container. 
Here's my docker-compose.yml
[docker-compose_redis-sentinel.zip](https://github.com/lgaticaq/redis-sentinel/files/1676703/docker-compose_redis-sentinel.zip)
No major change except the password field

**Comment by lgaticaq** [comment]
Sentinel only minitoring your redis instances. Only in the redis instance master or slave can run the redis commands (SET, GET, KEYS, etc). You need connect to sentinel with a custom client. For example in node is ioredis or redis-sentinel

**Comment by enekenasoa** [comment]
Hi,
So, for me, I had to expose both container (master/slave) ports. I thought each container had redis and sentinel instance. 
Thanks for your help.
